# Codabench GPU worker (NVIDIA)
services:
    worker1:
        image: codabench-erasinginvisible:latest
        # pull_policy: always
        container_name: worker1
        volumes:
            - ${HOST_DIRECTORY}/codabench:/codabench
            - ${HOST_DIRECTORY}/eval-program:/eval-program
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - .env
        restart: unless-stopped
        logging:
            options:
                max-size: 50m
                max-file: 3
        runtime: nvidia
        network_mode: host
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          device_ids: ['0']
                          capabilities:
                              - gpu
